batch_size: 1
data:
  dataset: labeled_fashion_mnist_inr
  dataset_path: ./data/fmnist_inrs/  # ./data/mnist_inr_phase_canon/
  split_path: ./data/fmnist_inrs/splits.json  #./data/mnist_inr_phase_canon/phase_canonicalized_mnist_splits.json  #
  image_size: [28,28]
  layer_layout: [2, 32, 32, 1]
  data_format: wb
  return_path: True
  switch_to_canon: False
